apiVersion: v1
kind: Service
metadata:
  name: appointment-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: appointment
  ports:
    - name: appointment
      protocol: TCP
      port: 3000
